### ISSUE TITLE
Slow juddery scroll when applied to elements

### ISSUE THREAD

**Issue by iantearle** [omorandi/TiViewShadow#3]
Hi, I have applied albeit version 0.1 to a tableview and a scrollview (not full width) and upon scrolling the views are extremely slow and judder down and up as you scroll. I couldn't see what 0.2 fixed or if it was just a module number bump.

**Comment by iantearle** [comment]
Should have tested first. 

Apologies. That is fixed, looks like the shadow is in sync with the view now. 

However, I am seeing the same issue as your other open issue on device.

**Comment by rborn** [comment]
The performance should be fine with v0.2, we changed the way the shadow is created, can you confirm please? Thnx.

**Comment by iantearle** [comment]
Yes, sorry 0.2 fixes this, this can be closed.
